version: '3.3'
services:
  node:
    image: ugly-map/node
    build: .
    ports:
      - 3000:3000
    volumes:
      - ./app/config:/usr/src/app/config
      - ./app/public:/usr/src/app/public
      - ./app/server.js:/usr/src/app/server.js
      - ./data:/usr/src/app/data
    command: npm run start
    restart: unless-stopped
